# Generated by theme-switch.py — do not edit by hand.
# Source palette: archeotech-frappe
# Replaces fish's frozen theme vars so shell colors track the active theme
# (new shells pick this up; run `exec fish` to refresh the current one).

set --global fish_color_autosuggestion #737994
set --global fish_color_cancel #e78284
set --global fish_color_command #8caaee
set --global fish_color_comment #838ba7
set --global fish_color_cwd #e5c890
set --global fish_color_cwd_root #e78284
set --global fish_color_end #ef9f76
set --global fish_color_error #e78284
set --global fish_color_escape #ea999c
set --global fish_color_gray #737994
set --global fish_color_history_current --bold
set --global fish_color_host #8caaee
set --global fish_color_host_remote #a6d189
set --global fish_color_keyword #e78284
set --global fish_color_normal #c6d0f5
set --global fish_color_operator #f4b8e4
set --global fish_color_option #a6d189
set --global fish_color_param #eebebe
set --global fish_color_quote #a6d189
set --global fish_color_redirection #f4b8e4
set --global fish_color_search_match --background=#414559
set --global fish_color_selection --background=#414559
set --global fish_color_status #e78284
set --global fish_color_user #81c8be
set --global fish_color_valid_path --underline
set --global fish_pager_color_background
set --global fish_pager_color_completion #c6d0f5
set --global fish_pager_color_description #737994
set --global fish_pager_color_prefix #f4b8e4
set --global fish_pager_color_progress #737994
set --global fish_pager_color_secondary_background
set --global fish_pager_color_secondary_completion
set --global fish_pager_color_secondary_description
set --global fish_pager_color_secondary_prefix
set --global fish_pager_color_selected_background
set --global fish_pager_color_selected_completion
set --global fish_pager_color_selected_description
set --global fish_pager_color_selected_prefix
